# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import interrealation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name of request')),
                ('my_own_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='set own price')),
                ('no_price', models.NullBooleanField(verbose_name='set no price')),
                ('symptoms', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('file_qr', models.FileField(blank=True, null=True, upload_to=interrealation.models.get_file_path)),
                ('doc_relation', models.ManyToManyField(blank=True, null=True, to='profiles.DocCategories', verbose_name='relation filed to Doc categories')),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
