# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-08 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import interrealation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20151208_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name of request')),
                ('my_own_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='set own price')),
                ('no_price', models.NullBooleanField(verbose_name='set no price')),
                ('symptoms', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('file', models.FileField(blank=True, null=True, upload_to=interrealation.models.get_file_path)),
                ('doc_relation', models.ManyToManyField(blank=True, null=True, to='profiles.DocCategories', verbose_name='relation filed to Doc categories')),
            ],
        ),
    ]
