# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-08 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interrealation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickrequest',
            old_name='file',
            new_name='file_qr',
        ),
    ]
